[package]

name = "glob"
version = "0.1.0"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/rust-lang/glob"
repository = "https://github.com/rust-lang/glob"
description = """
Support for matching file paths against Unix shell style patterns.
"""
